### ISSUE TITLE
TIPP disappears from OAI output

### ISSUE THREAD

**Issue by croqueGrec09** [openlibraryenvironment/gokb#210] opened 2020-02-28 15:38 UTC
Occurred in dev.

Whenever I set in a TIPP the property Depth from Fulltext to Empty (https://phaeton-dev.hbz-nrw.de/gokb/resource/show/org.gokb.cred.Package%3A236080), the whole TIPP disappears from the corresponding OAI extract.

**Comment by hornmo** [comment] 2020-02-28 17:41
Thanks for the report. This is caused by unexpected HQL behaviour (as described here: http://tomaszdziurko.com/2011/12/problem-withjpa-join-column-null-values-and-orderby/).

We'll have a fix in the next release, but we may also take this opportunity to make `coverageDepth` not-nullable (this is already validated for in integration imports anyway).

**Comment by hornmo** [comment] 2020-03-13 13:07
Fixed in #212

**Closed as completed by hornmo** 2020-03-13 13:07 UTC
Labels: bug, in progress
